# -*- coding: utf-8 -*-
"""face_emotion_image.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14gD_7wS9MPHyC0Tb9XQn-g3RvFmK27Z9
"""

!pip install deepface

import cv2

from deepface import DeepFace

from google.colab import files
uploaded = files.upload

img = cv2.imread('image1.jpg')

import matplotlib.pyplot as plt

import matplotlib.image as mpimg

plt.imshow(img)

plt.imshow(cv2.cvtColor(img, cv2.COLOR_BGR2RGB))

predictions = DeepFace.analyze(img)

predictions

predictions['dominant_emotion']

faceCascade = cv2.CascadeClassifier(cv2.data.haarcascades + 'haarcascade_frontalface_default.xml')

gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
faces = faceCascade.detectMultiScale(gray,1.1,4)

for x,y,w,h in faces:
  cv2.rectangle(img, (x,y), (x+w,y+h), (0,255,0), 2)

plt.imshow(cv2.cvtColor(img, cv2.COLOR_BGR2RGB))

font = cv2.FONT_HERSHEY_SIMPLEX

cv2.putText(img,
            predictions['dominant_emotion'],
            (0,50),
            font,1,
            (0,0,255),
            2,
            cv2.LINE_4);

plt.imshow(cv2.cvtColor(img, cv2.COLOR_BGR2RGB))

